### ISSUE TITLE
Please update the starter template with eui 23.1.0

### ISSUE THREAD

**Issue by rchavik** [elastic/next-eui-starter#4]

**Comment by Victordmdb** [comment]
After updating to anything after 19.0.0, getting many of these errors:

```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**Comment by chetanmajithiya** [comment]
@miukimiu 
i have created starter tempalte with v.23.3.0 (with JS project not typescript),
it's working but getting errors and creased app, when i use Collapsible nav.
https://elastic.github.io/eui/#/navigation/collapsible-nav
