### ISSUE TITLE
Inconsistent link opening on the home page

### ISSUE THREAD

**Issue by gavinwye** [elastic/next-eui-starter#64]
There are four links on the [homepage](https://elastic.github.io/next-eui-starter/) the first three open in a new tab/window but the 4th link opens in the same window. As these all go to a different site is the pattern to open all off-site links in a new window? 

Could we be consistent with the 4th link to https://codesandbox.io/

<img width="968" alt="image" src="https://user-images.githubusercontent.com/868772/162904545-b688f41f-db73-45dc-9e77-e8bd331a7ccf.png">

**Comment by miukimiu** [comment]
Thanks, @gavinwye for reporting this issue. 🙌🏽 

Do you want to open a PR to fix this? Or should I assign it to me?
